### ISSUE TITLE
how can i only run the detail place

### ISSUE THREAD

**Issue by HongYuLou** [cuhk-eda/Xplace#12]
I wanted to ask how can I just run your detail place part, because I found your detail place works so well

**Comment by liulixinkerry** [comment]
Currently, to only enable DP, you can remove/comment all the codes between [src/run_placement_nesterov.py#L138-L380](https://github.com/cuhk-eda/Xplace/blob/main/src/run_placement_nesterov.py#L138-L380), and then add the following code on [src/run_placement_nesterov.py#L382](https://github.com/cuhk-eda/Xplace/blob/main/src/run_placement_nesterov.py#L382).
```
node_pos, iteration, gp_end_time, gp_per_iter = data.node_pos, 0, time.time(), 0
```

**Comment by liulixinkerry** [comment]
Or you can also try our latest commit fcc9d0922c42a55a7546821035867c58bd876592. We include the command option `--global_placement`. You can set it to False to switch off GP.

**Comment by HongYuLou** [comment]
> Or you can also try our latest commit [fcc9d09](https://github.com/cuhk-eda/Xplace/commit/fcc9d0922c42a55a7546821035867c58bd876592). We include the command option `--global_placement`. You can set it to False to switch off GP.

Thank you for your help!The effect is excellent!
