### ISSUE TITLE
use cell inflate in superblue

### ISSUE THREAD

**Issue by EvenZ97** [cuhk-eda/Xplace#16]
Hi, if I want to use routability optimization on the benchmark Superblue, do I need to externally set up a router similar to NCTUGr to obtain the congestion map? And are there any other methods available?

**Comment by liulixinkerry** [comment]
If your dataset is based on bookshelf format, I suggest using NCTUgr to generate the congestion map. 

If your dataset is based on LEF/DEF format, you can use Xplace's internal router to generate the congestion map.

**Comment by EvenZ97** [comment]
Thank you very much for your response. I will try to see how to integrate NCTUgr into xplace for use.
