### ISSUE TITLE
Segmentation fault (core dumped) occurs when running GR

### ISSUE THREAD

**Issue by EvenZ97** [cuhk-eda/Xplace#18]
When I run the program on my own computer, using mgc_fft_1 and use_cell_inflate, a Segmentation fault (core dumped) occurs when calling GR, but no error occurs when running the program on the server. After careful investigation, I found that the number of batches and the number of nets are inconsistent. I would like to ask what causes this situation? The GPU of the server is A100, and the GPU of my computer is 3060. What do I need to do so that I can run it on my computer?
<img width="538" alt="微信图片_20241103215035" src="https://github.com/user-attachments/assets/34b7e238-058e-443e-8f84-452dee63f09a">
<img width="323" alt="微信图片_20241103215101" src="https://github.com/user-attachments/assets/9abd0a3c-b919-4110-84f4-822a9f6d4176">

**Comment by liulixinkerry** [comment]
Are you using the [`ispd2015_fix` benchmark](https://github.com/cuhk-eda/Xplace/blob/main/data/README.md) for both computers? 

My server also reports `9654840`.

**Comment by EvenZ97** [comment]
Yes, both ispd2015_fix, mgc_fft_1, but my wsl2 reports different.

**Comment by liulixinkerry** [comment]
I don't know why WSL2 crashed. My WSL2 also segmentfault for GR. I suggest using Linux instead.

**Comment by EvenZ97** [comment]
Thank you so much for your reply. The main reason is that I cannot use C++ Python joint debugging when running on the server, and the program cannot be loaded onto the process. I try to use other methods.
