### ISSUE TITLE
routability evalouation

### ISSUE THREAD

**Issue by EvenZ97** [cuhk-eda/Xplace#19]
Hello, I want to perform routability analysis, but when I use the first two routability analysis methods you provided, I don't get any results. When I use --final_route_eval True, I don't see the routability of the results. When I use CU-GR to get the results, there will be an IndexError: list index out of range error. Can I input a single data set or I need to input all the data sets of ispd2015 fix together for the test code? And how can I evaluate the routability of Placement solution
1. use --final_route_eval True
![Screenshot from 2024-12-16 17-00-26](https://github.com/user-attachments/assets/0213c8cb-fb14-4bc6-a6c9-4401e982990c)
2. use CU-GR
![Screenshot from 2024-12-16 17-03-49](https://github.com/user-attachments/assets/fb6fe365-17e9-41bb-ac17-18ea9446adc3)

**Comment by liulixinkerry** [comment]
The final_route_eval does not call the CUGR.

If you want to use CUGR for evaluation, you need to (1) call the CUGR (2) use the py script to parse.

```shell
# step 1
python -u run_cugr.py --dataset_root yourpath/Xplace/data/raw/ispd2015_fix --placement_root yourpath/Xplace/result/2000-01-01-00:00:00 | tee test_xplace_route.log
# step2
python run_cugr.py --parse --log_file ./test_xplace_route.log
```

You may refer to https://github.com/cuhk-eda/Xplace/blob/main/tool/cugr_ispd2015_fix/README.md

**Comment by EvenZ97** [comment]
Thank you for your reply, but what I mean is that I can't evaluate the routability after trying these two methods, they don't output the results. I want to ask why, and what kind of results will be output if the evaluation is successful.

**Comment by liulixinkerry** [comment]
May you provide the commands how you generate placement and eval the solution?

**Comment by EvenZ97** [comment]
Of course
1. use --final_route_eval
[test.log](https://github.com/user-attachments/files/18149752/test.log)
2. use CU-GR
![Screenshot from 2024-12-16 20-11-35](https://github.com/user-attachments/assets/ca773371-f1e7-405c-bcd9-3758fdafb29d)

**Comment by liulixinkerry** [comment]
I find out a bug in this script and fix it in the latest commit https://github.com/cuhk-eda/Xplace/commit/72cee91d48dc9134765bb8f03f9488ffa7293abf.

BTW, please make sure you use the `--run_all True` during placement. And set up the dataset root folder like `xxx/ispd2015_fix` instead of `xxx/ispd2015_fix/mgc_fft_1` during evaluation.

**Comment by EvenZ97** [comment]
Thanks! Is it true that --final_route_eval can only be used when --run_all is True and cannot be added when running single data set separately?

**Comment by EvenZ97** [comment]
sorry, I have another 2 problems，when I use --run_all True during placement
1. the placer can't do legalization
![Screenshot from 2024-12-16 21-06-33](https://github.com/user-attachments/assets/7390668a-e005-4c5b-a1b0-cb83cf54e103)
2. the second is when I run mgc superblue 12
![Screenshot from 2024-12-16 21-08-56](https://github.com/user-attachments/assets/f7923ff7-53c8-48b1-8b8a-a1ab6c25dd5e)

**Comment by liulixinkerry** [comment]
`--final_route_eval` can only be used when ` --use_cell_inflate` is `True`. You can use it for a single design or all designs.

If you want to enable `--final_route_eval` when ` --use_cell_inflate` is `False`. You may need to modify the code.

**Comment by liulixinkerry** [comment]
> sorry, I have another 2 problems，when I use --run_all True during placement
> 
> 1. the placer can't do legalization
>    ![Screenshot from 2024-12-16 21-06-33](https://private-user-images.githubusercontent.com/39229767/396106347-7390668a-e005-4c5b-a1b0-cb83cf54e103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTQ5MzIsIm5iZiI6MTczNDM1NDYzMiwicGF0aCI6Ii8zOTIyOTc2Ny8zOTYxMDYzNDctNzM5MDY2OGEtZTAwNS00YzViLWExYjAtY2I4M2NmNTRlMTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDEzMTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOGRmOTBlMjZhNWQwZjUzOWM0NzJjZWFhZTA2ZjYwMDI5ZDkzMDUyMWFlMThlMGEzODUwZGM3N2Q1MTg4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gdiZVX_bCwRftPoBhakHYJoaJNfUzecIdzfl-zlKhDU)
> 2. the second is when I run mgc superblue 12
>    ![Screenshot from 2024-12-16 21-08-56](https://private-user-images.githubusercontent.com/39229767/396106963-f7923ff7-53c8-48b1-8b8a-a1ab6c25dd5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTQ5MzIsIm5iZiI6MTczNDM1NDYzMiwicGF0aCI6Ii8zOTIyOTc2Ny8zOTYxMDY5NjMtZjc5MjNmZjctNTNjOC00OGIxLThiOGEtYTFhYjZjMjVkZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDEzMTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYmZlN2Y3MmU5YTE2ZjdiMWZhMmUzZTBhMzRkMzNiYWYxZWM2ZDA5ODljNGUxZTBmNGIxNjZkNDVkMzM0NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oQusqI_8HjtuWp5q_APB4jzHF17YowrTgD-lnMhF76w)



For 1, I am not sure why this error occurs. Could you provide your CUDA and PyTorch versions? I need some time to look into that.
For 2, it should be `mgc_superblue12` instead of `mgc_superblue_12`.

**Comment by EvenZ97** [comment]
thanks a lot!
1. my cuda version:
![Screenshot from 2024-12-16 21-26-56](https://github.com/user-attachments/assets/e0c85711-a13f-4947-bf8a-f9affe393d29)
2. my pytorch version is 2.0.1+cu118

**Comment by liulixinkerry** [comment]
I try to fix the legalization bug in the latest commit. Please pull and re-try. @EvenZ97

**Comment by EvenZ97** [comment]
Thank you for your reply，I will try the new one！
