### ISSUE TITLE
undefined symbol: curandCreateGenerator

### ISSUE THREAD

**Issue by ZhiangWang033** [cuhk-eda/Xplace#3]
Hi, 

I tried to play with Xplace based on the instructions in the README file.

I have successfully installed the Xplace with torch 2.0.1+cu118 and cuda11.8.

Install the project...
-- Install configuration: "Release"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libflute.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libflute.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libxplace_common.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libxplace_common.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/dct_cuda.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/dct_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/density_map_cuda.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/density_map_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/draw_placement.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/draw_placement.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/flute_cpp.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/flute_cpp.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libdp.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libdp.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpudp.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpudp.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libggr.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libggr.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpugr.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpugr.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/hpwl_cuda.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/hpwl_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/io_parser.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/io_parser.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/routedp.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/routedp.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
-- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/wa_wirelength_hpwl_cuda.cpython-38-x86_64-linux-gnu.so
-- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/wa_wirelength_hpwl_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"

But when I tries to run the benchmarks,  it failed ...

python main.py --dataset ispd2005 --design_name adaptec1 --load_from_raw True --detail_placement True

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from utils import *
  File "/home/zhiang/RePlAceCUDA/Xplace/utils/__init__.py", line 1, in <module>
    from .io_parser import IOParser
  File "/home/zhiang/RePlAceCUDA/Xplace/utils/io_parser.py", line 2, in <module>
    from cpp_to_py import io_parser
  File "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/__init__.py", line 14, in <module>
    from .cpybin import (
ImportError: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libdp.so: undefined symbol: curandCreateGenerator

**Comment by liulixinkerry** [comment]
Hi @ZhiangWang033 May you also provide your OS, I want to try it in Docker.

**Comment by ZhiangWang033** [comment]
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

**Comment by liulixinkerry** [comment]
@ZhiangWang033 
It seems that CUDA 11.8 does not officially support CentOS 8 as shown in [website](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=CentOS). 
Could you try to use [CUDA 11.6](https://developer.nvidia.com/cuda-11-6-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=CentOS&target_version=8) and [PyTorch 1.13](https://pytorch.org/get-started/previous-versions/) to see whether it is workable?

**Comment by liulixinkerry** [comment]
@ZhiangWang033 Besides, please try to remove [this line](https://github.com/cuhk-eda/Xplace/blob/main/cpp_to_py/__init__.py#L23) and see whether the GP can run or not. If not, there should be some other problems.

**Comment by ZhiangWang033** [comment]
Thanks,  after removing the line you suggested.  I can run the tool now.  But I got a new error ...
![image](https://github.com/cuhk-eda/Xplace/assets/69448998/b26af36c-6179-4892-b263-1dcc9169c4f2)

**Comment by liulixinkerry** [comment]
Hi, could you try to modify https://github.com/cuhk-eda/Xplace/blob/main/cpp_to_py/gpudp/CMakeLists.txt#L27 to the following line with linking to CUDA::curand? 
```
target_link_libraries(dp PRIVATE torch ${TORCH_PYTHON_LIBRARY} xplace_common flute dp_cuda_tmp pthread CUDA::curand)
```
and add `find_package(CUDAToolkit)` in https://github.com/cuhk-eda/Xplace/blob/main/CMakeLists.txt#L67
```
if (TORCH_ENABLE_CUDA)
  find_package(CUDA 11.4)
  find_package(CUDAToolkit)
```
Then add back https://github.com/cuhk-eda/Xplace/blob/main/cpp_to_py/__init__.py#L23 
I think it would fix your first issue mentioned in:


> Hi,
> 
> I tried to play with Xplace based on the instructions in the README file.
> 
> I have successfully installed the Xplace with torch 2.0.1+cu118 and cuda11.8.
> 
> Install the project... -- Install configuration: "Release" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libflute.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libflute.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libxplace_common.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libxplace_common.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/dct_cuda.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/dct_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/density_map_cuda.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/density_map_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/draw_placement.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/draw_placement.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/flute_cpp.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/flute_cpp.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libdp.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libdp.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpudp.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpudp.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libggr.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libggr.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpugr.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/gpugr.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/hpwl_cuda.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/hpwl_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/io_parser.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/io_parser.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/routedp.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/routedp.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin" -- Installing: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/wa_wirelength_hpwl_cuda.cpython-38-x86_64-linux-gnu.so -- Set runtime path of "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/wa_wirelength_hpwl_cuda.cpython-38-x86_64-linux-gnu.so" to "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin"
> 
> But when I tries to run the benchmarks, it failed ...
> 
> python main.py --dataset ispd2005 --design_name adaptec1 --load_from_raw True --detail_placement True
> 
> Traceback (most recent call last): File "main.py", line 1, in from utils import * File "/home/zhiang/RePlAceCUDA/Xplace/utils/**init**.py", line 1, in from .io_parser import IOParser File "/home/zhiang/RePlAceCUDA/Xplace/utils/io_parser.py", line 2, in from cpp_to_py import io_parser File "/home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/**init**.py", line 14, in from .cpybin import ( ImportError: /home/zhiang/RePlAceCUDA/Xplace/cpp_to_py/cpybin/libdp.so: undefined symbol: curandCreateGenerator


Reference: https://github.com/pytorch/pytorch/issues/69666

**Comment by liulixinkerry** [comment]
As for your second issue:
> Thanks, after removing the line you suggested. I can run the tool now. But I got a new error ... ![image](https://user-images.githubusercontent.com/69448998/241340571-b26af36c-6179-4892-b263-1dcc9169c4f2.png)

it is due to the API change of PyTorch 2.0.

I fixed these two problems in the two latest commits (9cc7ea4 and 0aa58ed). Please pull it, rebuild the project, and try to see whether there are any other problems.

**Comment by ZhiangWang033** [comment]
Thank you very much.  It works now.
