### ISSUE TITLE
How to run designs with multiple lefs

### ISSUE THREAD

**Issue by ZhiangWang033** [cuhk-eda/Xplace#5]
I have a design with multiple lefs.  How to use XPlace using this command:  python main.py --custom_path lef:data/raw/toy_input.lef,def:data/raw/toy_input.def,design_name:toy,benchmark:test --load_from_raw True --detail_placement True

**Comment by liulixinkerry** [comment]
How many lefs do you need？ If only need tech_lef and cell_lef, you just need to replace `lef:...` by `...,tech_lef:...,cell_lef:...,`.

**Comment by ZhiangWang033** [comment]
I also have three macro lefs.

**Comment by Rholais** [comment]
> I also have three macro LEFs.

Hi Zhiang, maybe you can try pasting the LEFs in a single file?

**Comment by liulixinkerry** [comment]
I have supported multiple lefs. Please refer to [examples.json](https://github.com/cuhk-eda/Xplace/blob/main/examples/examples.json) and run Xplace with `python main.py --custom_json examples/examples.json`.

Thank you!
