### ISSUE TITLE
about cmake version

### ISSUE THREAD

**Issue by Mrsun0** [cuhk-eda/Xplace#6]
It seems that the minimum required version of CMake is 3.17 because the cmake command **_find_package(CUDAToolkit)_** is only supported in versions 3.17 and higher.
<img width="397" alt="image" src="https://github.com/cuhk-eda/Xplace/assets/59727595/40aaa2ed-e206-46dc-95ea-a9f389346ad2">

**Comment by liulixinkerry** [comment]
Thanks for your notification! I have updated the readme correspondingly.
